### ISSUE TITLE
🎴 Cards getting cached on github markdown

### ISSUE THREAD

**Issue by crizmo** [crizmo/DiscordCards#1]
The API card seems to get cached on GitHub markdown but works perfectly fine on sites
Am i setting the headers wrong or some wrong code ?! 

card endpoint - [code](https://github.com/crizmo/breeze/blob/main/server-dcez/lib/api.js)
compact endpoint - [code](https://github.com/crizmo/breeze/blob/main/server-dcez/lib/api_xomp.js)

**Comment by ghost** [comment]
Hey there! perhaps you could add these headers/or just use the package, I've had a project like this in the past and it was a life saver!

https://github.com/helmetjs/nocache/blob/main/index.js#L3-L9

**Comment by crizmo** [comment]
:hushed: trying it rn !
Thanks for the help

**Comment by crizmo** [comment]
It works !! Thanks
